FROM ubuntu:latest

RUN apt-get update
RUN apt-get install -y cron
RUN apt-get install -y curl
RUN apt-get install -y net-tools
RUN apt-get install -y iproute2
RUN apt-get install -y lshw
RUN apt-get install -y dnsutils
RUN apt-get install -y iputils-ping
RUN apt-get install -y jq
RUN apt-get install -y lshw

ADD ./data/cronjob.sh /cronjob.sh
ADD ./data/endPointQuery.sh /endPointQuery.sh
ADD ./startup.sh /startup.sh
ADD ./service/daemon.sh /daemon.sh

RUN chmod a+x /cronjob.sh
RUN chmod a+x /endPointQuery.sh
RUN chmod a+x /startup.sh
RUN chmod a+x /daemon.sh

RUN crontab -l | { cat; echo "* * * * * /cronjob.sh > /proc/1/fd/1 2>/proc/1/fd/2"; } | crontab -


RUN touch /var/log/cron.log
RUN mkdir /data
RUN touch /data/id
RUN touch /data/serverPath

CMD ["./startup.sh"]
