version: "3"
services:
  watsupg:
    image: yelloelefant/watsupg
    container_name: watsupg-client
    privileged: true
    environment:
      - serverPrivateIp=192.168.1.29
      - serverDomainName=watsupg.yelloelefant.com
      - token=123456789
      - TZ=Pacific/Auckland
    network_mode: host
    volumes:
      - ./clientData:/data
      - /sys:/sys:ro
      - /proc:/proc
      - /dev:/dev:ro
    security_opt:
      - apparmor=unconfined
    restart: unless-stopped
