FROM ubuntu:latest

RUN apt-get update
RUN apt-get install -y cron
RUN apt-get install -y curl
RUN apt-get install -y net-tools
RUN apt-get install -y iproute2

ADD ./data/cronjob /cronjob

ADD ./data/cronjob.sh /cronjob.sh

RUN chmod a+x /cronjob.sh
RUN chmod a+x /cronjob

RUN crontab -l | { cat; echo "* * * * * /cronjob.sh"; } | crontab -


RUN touch /var/log/cron.log
RUN mkdir /data
RUN touch /data/id

CMD ["cron", "-f"]
