version: "3"
services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "2525:80"
    networks:
      - internal
    volumes:
      - ../Pages/:/var/www/html/
      - /logs/nginx:/var/log/nginx/+
    restart: unless-stopped
  php:
    image: php:fpm-alpine
    build: ./
    networks:
      - internal
    depends_on:
      - redis
    volumes:
      - ../Pages/:/var/www/html
    restart: unless-stopped
  redis:
    container_name: redis
    image: redis:6.2-alpine
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - ../ClientData:/data
    environment:
      - REDIS_DATABASES=16
    networks:
      - internal

networks:
  internal:
    driver: bridge
